### ISSUE TITLE
Stragglers

### ISSUE THREAD

**Issue by clifton** [ATXDAO/website#10]
people to add (comment below and i can add others)

| | name | address | notes |
|-|-|-|-|
| 🔳 | @madzz |  `0xA0184E8b5bAE11b5fA5b4950D0B61C299112E01D` | kyle's friend
| 🔳  | `arno#8826` | `0x648d3d0438B1E4c7EB641f67E38ca86cf975ca8e ` |
| 🔳 | `Masta Zamsta#8817` | `0x5b062c6551BD1116B4d77016b31C6B8c4767F4ad` |
| 🔳 | `srust99 ` | `0x5d40247Ee017323C8b09434B917Ba6F4ED4eef14 ` | original whitelist
| 🔳 | `schisms#5300` | `0x2a8EaA7C151D43BEE03073BD4e5E32Ed4673c5ff ` | Mason friend
| 🔳 | `Sam L#9580` | `0xF17e5EBb3A1972C4Cb6a27D717d5f55BbFfedb46` | Mason brother, works w/ govt
| 🔳 | `JofoJ#9973` | `0xD859dB3F76C5a23f3626903B6ECc7e49c49C35b8 ` | Director of platform at Capital Factory
| 🔳 | `Xin#5226` | `0x73Eba8e4173CE8D4186dDDe82fBaf123E2Ad7DCd ` | couldn't get in contact with us

**Comment by masonleenaugh** [comment]
schisms#5300 - 0x2a8EaA7C151D43BEE03073BD4e5E32Ed4673c5ff - Mason friend
Sam L#9580 0xF17e5EBb3A1972C4Cb6a27D717d5f55BbFfedb46 - Mason brother, works in govt: built vaccine tracking system
JofoJ#9973 - 0xD859dB3F76C5a23f3626903B6ECc7e49c49C35b8 - Director of platform at Capital Factory

**Comment by josephflu** [comment]
srust99 - 0x5d40247Ee017323C8b09434B917Ba6F4ED4eef14 - original whitelist

**Comment by clifton** [comment]
from jon 0xE603C11017EBCEfFaa32084f9BCAD508cbB0D133
