### ISSUE TITLE
eventbrite integration

### ISSUE THREAD

**Issue by kungfuflex** [ATXDAO/website#15]
In the pages/events.js, use the eventbrite SDK off of npm to fetch ATXDAO events in getServerProps and render previews

If the user is logged in, connected, and has an NFT, the link to eventbrite will create a modal before navigating the user to their platform, where they are able to first create a signature of { tokenId, eventId } with MetaMask to prove they own an NFT, then the handler to accept the signature will create a discount class + code (same string for discount class name and the code, there is only one discount code valid for the nft holder per event)

The API route on our website will use the eventbrite SDK to create a discount class and code to show to the user, with a button to copy it, then underneath is a button to proceed to the eventbrite page, once they have had an opportunity to copy their discount code to the clipboard

The discount should just give the NFT holder 100% off when he inputs it into the eventbrite registration page

The discount code will just be the last 8 chars in the signature

You use eip712 to create the signature, some code to verify an eip712 signature  can be seen in https://github.com/nifty-door/nifty-nfc-daemon/blob/master/lib/verify.js

Some code to generate one can be seen here: https://github.com/zerodao-finance/zero-protocol/blob/master/lib/zero.ts#L223

The signer object can be created from the account context in the app

**Comment by clifton** [comment]
closed by #24
